### ISSUE TITLE
--help is wrong

### ISSUE THREAD

**Issue by staranto** [sylwit/terraform-cleaner#1]
```
Flags:
  -h, --help          help for terraform-cleaner
      --locals        Display only unused locals
      --unused-only   Display only unused values
      --variables     Display only unused variables
```

Should "only unused" by stricken from both --locals and --variables.

--locals shows all locals.  
--variables shows all variables.
--locals --unused-only shows only unused locals.
--variables --unused-only shows only unused variables.

**Comment by sylwit** [comment]
Thanks for raising this @staranto 

It's not fix in https://github.com/sylwit/terraform-cleaner/releases/tag/v0.0.4
