### ISSUE TITLE
Make terraform-cleaner pre-commit installable

### ISSUE THREAD

**Issue by richardj-bsquare** [sylwit/terraform-cleaner#2]
Add a .pre-commit-hooks.yaml and make this tool a pre-commit hook itself!

**Comment by antonbabenko** [comment]
I've just opened a similar issue but in another repository - https://github.com/antonbabenko/pre-commit-terraform/issues/504

**Comment by sylwit** [comment]
Since @antonbabenko considers adding this tool to his precommit, I would suggest to continue the discussion on this thread https://github.com/antonbabenko/pre-commit-terraform/issues/504
